### ISSUE TITLE
Return value for a single result

### ISSUE THREAD

**Issue by alongat** [bhmj/jsonslice#11]
Calling Get with `$.store.book[0].author` on the following json
```
{
	"store": {
		"book": [
			{
				"category": "fiction",
				"author": "J. R. R. Tolkien",
				"title": "The Lord of the Rings",
				"isbn": "0-395-19395-8",
				"price": 22.99
			}
		]
	}
}
```
returns  `"J. R. R. Tolkien"` rather than `[ "J. R. R. Tolkien" ]`

According to jsonpath specification https://goessner.net/articles/JsonPath/index.html#e2
> Please note, that the return value of jsonPath is an array, which is also a valid JSON structure.
Also see https://jsonpath.com/ examples

Moreover the result has \" in the string, meaning the resulting string will look like `""J. R. R. Tolkien""`...

Is this by design? am I missing anything? :)

**Comment by bhmj** [comment]
Yes, this is by design, see par. 2 [here](https://github.com/bhmj/jsonslice#syntax-features). If you want to get an array, use the slice reference instead (`$.store.book[0:1].author`).

The result is a JSON value which happens to be a string, and JSON spec requires a string to be quoted.

**Comment by alongat** [comment]
Cool, thanks for clarifying!
