### ISSUE TITLE
Nil Pointer dereference for an invalid query

### ISSUE THREAD

**Issue by dschowta** [bhmj/jsonslice#12]
dear @bhmj, 
``` go
package main 
import "github.com/bhmj/jsonslice"
import "fmt"

func main() {
    var data = []byte(`
    { "sku": [ 
        { "id": 1, "name": "Bicycle", "price": 160, "extras": [ "flashlight", "pump" ] },
        { "id": 2, "name": "Scooter", "price": 280, "extras": [ "helmet", "gloves", "spare wheel" ] }
      ]
    } `)

    a, _ := jsonslice.Get(data, "$*")
  
    fmt.Println(string(a)) // 160

}
```
This program crashes at this [line](https://github.com/bhmj/jsonslice/blob/882a55fa931cb1034965bd34d2366b6b5fb012ae/jsonslice.go#L157) all the times. The behaviour is same with such queries starting with any character from  [keyterminator](https://github.com/bhmj/jsonslice/blob/882a55fa931cb1034965bd34d2366b6b5fb012ae/jsonslice.go#L191). 
Though the query is invalid, crashing is not expected.

Thank you.

**Comment by bhmj** [comment]
Fixed: https://github.com/bhmj/jsonslice/releases/tag/1.0.4
