### ISSUE TITLE
Use semantic versioning

### ISSUE THREAD

**Issue by farshidtz** [bhmj/jsonslice#13]
Hi,

Thank you for this very useful package.

It would be great if you use semantic versioning in Git tags, otherwise it will not be possible to import the specific versions with Go Module. 

With semantic versioning, the current version should be `v1.0.4` instead of `1.0.4`.

https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
https://github.com/golang/go/wiki/Modules#semantic-import-versioning

Cheers

**Comment by bhmj** [comment]
Hello,
thanks for suggestion, I changed the versioning in tags from v1.0.0 up to the latest one.
