### ISSUE TITLE
deepscan issue

### ISSUE THREAD

**Issue by edodekel** [bhmj/jsonslice#15]
two similar jsonpath queries give different results:

data:=[]byte(`{
  "apiVersion": "v1",
  "kind": "Pod",
  "spec": {
    "containers": [
      {
        "name": "c1",
        "image": "busybox",
        "resources": {
          "limits": {
            "cpu": "2"
          }
        }
      },
      {
        "name": "c2",
        "image": "busybox",
        "resources": {
          "limits": {
            "cpu": "2"
          }
        }
      }
    ]
  }
}`)

**jsonslice.Get(data, "$.spec.containers[:]")**

gives the expected result:

[{
        "name": "c1",
        "image": "busybox",
        "resources": {
          "limits": {
            "cpu": "2"
          }
        }
      },{
        "name": "c2",
        "image": "busybox",
        "resources": {
          "limits": {
            "cpu": "2"
          }
        }
      }]

**BUT:**

**jsonslice.Get(data, "$..spec.containers[:]")**
gives:

[{
    "**containers**": [
      {
        "name": "c1",
        "image": "busybox",
        "resources": {
          "limits": {
            "cpu": "2"
          }
        }
      },
      {
        "name": "c2",
        "image": "busybox",
        "resources": {
          "limits": {
            "cpu": "2"
          }
        }
      }
    ]
  }]

**Comment by bhmj** [comment]
Working on a fix

**Comment by bhmj** [comment]
Fixed in [release 1.0.5](https://github.com/bhmj/jsonslice/releases/tag/v1.0.5)

**Comment by edodekel** [comment]
thanks

**Comment by edodekel** [comment]
jsonslice.Get(data, "$.spec.containers[:]")

gives the expected result:

[{
"name": "c1",
"image": "busybox",
"resources": {
"limits": {
"cpu": "2"
}
}
},{
"name": "c2",
"image": "busybox",
"resources": {
"limits": {
"cpu": "2"
}
}
}]

BUT:

jsonslice.Get(data, "$..spec.containers[:]")

gives double square brackets. 

[[{
"name": "c1",
"image": "busybox",
"resources": {
"limits": {
"cpu": "2"
}
}
},{
"name": "c2",
"image": "busybox",
"resources": {
"limits": {
"cpu": "2"
}
}
}]]

is it the expected result for deep scan?

**Comment by bhmj** [comment]
It is, because `$.spec.containers[:]` gives you a single array of all elements of `containers`, but `$..spec.containers[:]` scans the input for all the`spec.containers[:]` entries (there can be many of them) and puts them all in array. Each entry happens to be an array as stated above. In this particular case there is only one entry found, thus [ [...] ].

**Comment by edodekel** [comment]
so it is as designed. thanks
