### ISSUE TITLE
 the start index and end index of the queried string in the original string

### ISSUE THREAD

**Issue by GenePaal** [bhmj/jsonslice#23]

**Comment by GenePaal** [comment]
I want to get the start index and end index of the queried string in the original string, how can I do it?

**Comment by bhmj** [comment]
This library is not intended to get an _index_ of a queried string, it is intended to get a _value_. So in case of
```
{ "key_a": "abc", "key_b": "abc" }
```
and the query 
```
$.key_b
```
you will get `"abc"` as a result and you will not be able to distinguish first `"abc"` occurrence from the second one in the original json. Sorry to disappoint you, but that's the way it works.
