### ISSUE TITLE
can you support more functions?

### ISSUE THREAD

**Issue by aelous** [bhmj/jsonslice#4]
For example: 

Function | Description | Output
-- | -- | --
min() | Provides the min value of an array of numbers | Double
max() | Provides the max value of an array of numbers | Double
avg() | Provides the average value of an array of numbers | Double

**Comment by bhmj** [comment]
No problemo, man, but there are some questions to be answered )

What if an array does not contain decimals? What if an array contains decimals along with different data types, like strings or objects? What should I return if array is empty? Should it be an error or some predefined constant?

I haven't seen any specs on these functions applied to jsonpath, have you?
