### ISSUE TITLE
Clarify Get vs. GetArrayElements

### ISSUE THREAD

**Issue by cburgmer** [bhmj/jsonslice#5]
I'm trying to understand whether calling `Get` is the right answer for my use case. I'm running `$..key` against the following and yield `"top"` only:

```
{
    "object": {
        "key": "value",
        "array": [
            {"key": "something"},
            {"key": {"key": "russian dolls"}}
        ]
    },
    "key": "top"
}
```

Expected:
```
[
  "top",
  "value",
  "something",
  {
    "key": "russian dolls"
  },
  "russian dolls"
]
```

See https://github.com/cburgmer/json-path-comparison/blob/Golang_github.com-bhmj-jsonslice/implementations/Golang_github.com-bhmj-jsonslice/main.go for the code.

**Comment by bhmj** [comment]
Hello. Unfortunately the deepscan operator (`..`) you are trying to use is not implemented yet, as indicated in a roadmap. I'm planning to implement it soon though.

**Comment by cburgmer** [comment]
Thanks. I wasn't sure whether I should be using `GetArrayElements` instead.
Does it only exist to get a smaller slice?

**Comment by bhmj** [comment]
`GetArrayElements` is an auxiliary method intended to get separate array elements, instead of one large slice of bytes returned by `Get`.

**Comment by cburgmer** [comment]
Thx. Happy to have this issue closed after the clarification.
