### ISSUE TITLE
changed behaviour for arrays?

### ISSUE THREAD

**Issue by edodekel** [bhmj/jsonslice#8]
jsonpath := "$.a.b[:].['c','d']"
	jsonRaw:=[]byte(`{"a":{"b":[{"c":"cc1","d":"dd1"},{"c":"cc2","d":"dd2"}]}}`)
	result, err := jsonslice.Get(jsonRaw, jsonpath)

the result is:
["cc1","dd1","cc2","dd2"]

it used to be:
[["cc1","dd1"],["cc2","dd2"]]

which makes more sense

**Comment by bhmj** [comment]
Fixed that for now + planning to add an option to select between "nested" and "plain" aggregation modes
